# PyTorch basics
- Since PyTorch is getting popular
- We'll learn PyTorch basics in this notebook

---

# Import

In [ ]:
import torch

---

# Examples
- scalar
- vector
- matrix
- tensor

In [3]:
scalar = torch.tensor(3.14)
print(scalar) # tensor(3.1400)

tensor(3.1400)


In [4]:
vector = torch.tensor([1.0, 2.0, 3.0])
print(vector)

tensor([1., 2., 3.])


In [5]:
matrix = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
tensor = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(tensor)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


---

# numpy to tensor

In [7]:
import numpy as np

np_arr = np.array([[1, 2], [3, 4]])
torch_tensor = torch.from_numpy(np_arr)
print(np_arr)
print(torch_tensor)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


---

# tensor to numpy

In [8]:
tensor = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
np_arr = tensor.numpy()
print(np_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


---

# Fully Connected Layer (Linear Layer)

In [9]:
layer = torch.nn.Linear(in_features=4, out_features=2)
print(layer)
x = torch.rand(1, 4)  # input batch with 4 features
print(x)
out = layer(x)
print(out)

Linear(in_features=4, out_features=2, bias=True)
tensor([[0.3442, 0.1684, 0.5057, 0.0043]])
tensor([[-0.4281,  0.1108]], grad_fn=<AddmmBackward0>)


---

# Activation Functions

## ReLU

In [12]:
relu = torch.nn.ReLU()
out_relu = relu(out)
print(out_relu)

tensor([[0.0000, 0.1108]], grad_fn=<ReluBackward0>)


## Sigmoid

In [13]:
sigmoid = torch.nn.Sigmoid()
out_sigmoid = sigmoid(out)
print(out_sigmoid)

tensor([[0.3946, 0.5277]], grad_fn=<SigmoidBackward0>)


## Tanh

In [14]:
tanh = torch.nn.Tanh()
out_tanh = tanh(out)
print(out_tanh)

tensor([[-0.4037,  0.1103]], grad_fn=<TanhBackward0>)


---

# Activation functions

In [18]:
out_all = out
print(out_all)
out_all = torch.relu(out_all)
print(out_all)
out_all = torch.sigmoid(out_all)
print(out_all)
out_all = torch.tanh(out_all)
print(out_all)

tensor([[-0.4281,  0.1108]], grad_fn=<AddmmBackward0>)
tensor([[0.0000, 0.1108]], grad_fn=<ReluBackward0>)
tensor([[0.5000, 0.5277]], grad_fn=<SigmoidBackward0>)
tensor([[0.4621, 0.4836]], grad_fn=<TanhBackward0>)


---

# Loss Functions

## MSE Loss (Regression)

In [19]:
loss_fn = torch.nn.MSELoss()
target = torch.tensor([[0.0, 1.0]])
loss = loss_fn(out, target)
print(loss)

tensor(0.4870, grad_fn=<MseLossBackward0>)


## CrossEntropyLoss (Classification)

In [20]:
ce_loss_fn = torch.nn.CrossEntropyLoss()
logits = torch.rand(1, 3)  # raw scores (not softmaxed)
target_class = torch.tensor([2])  # class index
loss = ce_loss_fn(logits, target_class)
print(loss)

tensor(1.2346)


---

# Optimizer

In [21]:
model = torch.nn.Linear(4, 2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

## Training Loop (Simple Example)

In [22]:
def test():
    for epoch in range(10):
        x = torch.rand(1, 4)
        target = torch.tensor([[0.0, 1.0]])

        out = model(x)
        loss = torch.nn.functional.mse_loss(out, target)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(f"Epoch {epoch}, Loss: {loss.item()}")
test()

Epoch 0, Loss: 0.6918522715568542
Epoch 1, Loss: 1.0173901319503784
Epoch 2, Loss: 0.2578909993171692
Epoch 3, Loss: 0.5979954600334167
Epoch 4, Loss: 0.6437032222747803
Epoch 5, Loss: 0.8829860687255859
Epoch 6, Loss: 0.755384087562561
Epoch 7, Loss: 0.7139490842819214
Epoch 8, Loss: 0.6853145956993103
Epoch 9, Loss: 0.20261052250862122


---

# Mini Neural Network Example

## Define class

In [25]:
import torch
import torch.nn as nn

# Define model
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(4, 8)
        self.act1 = nn.ReLU()
        self.fc2 = nn.Linear(8, 2)

    def forward(self, x: torch.Tensor):
        x = self.fc1(x)
        x = self.act1(x)
        x = self.fc2(x)
        return x

## Train

In [26]:
def test():

    model = MLP()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    loss_fn = nn.MSELoss()

    for epoch in range(20):
        x = torch.rand(10, 4)
        target = torch.rand(10, 2)

        out = model(x)
        loss = loss_fn(out, target)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")
test()

Epoch 0, Loss: 0.6074
Epoch 1, Loss: 0.6466
Epoch 2, Loss: 0.5835
Epoch 3, Loss: 0.6002
Epoch 4, Loss: 0.5081
Epoch 5, Loss: 0.4339
Epoch 6, Loss: 0.3963
Epoch 7, Loss: 0.2702
Epoch 8, Loss: 0.2020
Epoch 9, Loss: 0.3615
Epoch 10, Loss: 0.2909
Epoch 11, Loss: 0.2780
Epoch 12, Loss: 0.2191
Epoch 13, Loss: 0.2434
Epoch 14, Loss: 0.2144
Epoch 15, Loss: 0.1419
Epoch 16, Loss: 0.1861
Epoch 17, Loss: 0.1995
Epoch 18, Loss: 0.1378
Epoch 19, Loss: 0.0839


---

# Classification (3 classes)

In [28]:
class Classifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(4, 8)
        self.act1 = nn.ReLU()
        self.fc2 = nn.Linear(8, 3)  # 3 classes

    def forward(self, x: torch.Tensor):
        return self.fc2(self.act1(self.fc1(x)))

def test():
    model = Classifier()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    loss_fn = nn.CrossEntropyLoss()

    for epoch in range(20):
        x = torch.rand(10, 4)
        target = torch.randint(0, 3, (10,))  # class labels: 0, 1, 2

        logits = model(x)
        loss = loss_fn(logits, target)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")
test()

Epoch 0, Loss: 1.2017
Epoch 1, Loss: 1.0505
Epoch 2, Loss: 1.0817
Epoch 3, Loss: 1.1032
Epoch 4, Loss: 1.1096
Epoch 5, Loss: 1.1330
Epoch 6, Loss: 1.1253
Epoch 7, Loss: 1.1287
Epoch 8, Loss: 1.0828
Epoch 9, Loss: 1.0940
Epoch 10, Loss: 1.1991
Epoch 11, Loss: 1.1117
Epoch 12, Loss: 1.0777
Epoch 13, Loss: 1.0492
Epoch 14, Loss: 1.1535
Epoch 15, Loss: 1.1025
Epoch 16, Loss: 1.1236
Epoch 17, Loss: 1.0571
Epoch 18, Loss: 1.1035
Epoch 19, Loss: 1.0740


---

# Dataset and DataLoader

In [32]:
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn

class MyDataset(Dataset): # type: ignore
    def __init__(self):
        self.data = torch.rand(100, 4)  # 100 samples, 4 features
        self.labels = torch.randint(0, 3, (100,))  # 3 classes: 0, 1, 2

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx: int):
        return self.data[idx], self.labels[idx]

def test():

    # Model for 4 input features → 3 class logits
    model = nn.Sequential(
        nn.Linear(4, 16),
        nn.ReLU(),
        nn.Linear(16, 3)
    )

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-2)
    loss_fn = nn.CrossEntropyLoss()

    dataset = MyDataset()
    loader = DataLoader(dataset, batch_size=16, shuffle=True)

    for epoch in range(5):
        for x_batch, y_batch in loader:
            logits = model(x_batch)
            loss = loss_fn(logits, y_batch)

            print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

test()

Epoch 0, Loss: 1.1069
Epoch 0, Loss: 1.0435
Epoch 0, Loss: 1.1790
Epoch 0, Loss: 1.0672
Epoch 0, Loss: 1.1153
Epoch 0, Loss: 1.0186
Epoch 0, Loss: 1.2062
Epoch 1, Loss: 1.0566
Epoch 1, Loss: 1.1233
Epoch 1, Loss: 1.0410
Epoch 1, Loss: 1.0855
Epoch 1, Loss: 1.1008
Epoch 1, Loss: 1.0626
Epoch 1, Loss: 1.0617
Epoch 2, Loss: 1.1012
Epoch 2, Loss: 1.0585
Epoch 2, Loss: 1.1075
Epoch 2, Loss: 1.0811
Epoch 2, Loss: 1.0388
Epoch 2, Loss: 1.0859
Epoch 2, Loss: 1.0341
Epoch 3, Loss: 1.0681
Epoch 3, Loss: 1.0304
Epoch 3, Loss: 1.1523
Epoch 3, Loss: 1.0126
Epoch 3, Loss: 1.0237
Epoch 3, Loss: 1.1301
Epoch 3, Loss: 1.1867
Epoch 4, Loss: 1.0649
Epoch 4, Loss: 1.0430
Epoch 4, Loss: 0.9975
Epoch 4, Loss: 1.0505
Epoch 4, Loss: 1.1943
Epoch 4, Loss: 1.0473
Epoch 4, Loss: 1.1431


---

# solve MNIST

In [36]:
import torch
from torch import nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

def test():

    # MNIST loaders
    transform = transforms.ToTensor()
    train = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
    test = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

    train_loader = DataLoader(train, batch_size=64, shuffle=True)
    test_loader = DataLoader(test, batch_size=64)

    # Simple model
    model = nn.Sequential(
        nn.Flatten(),
        nn.Linear(28 * 28, 128),
        nn.ReLU(),
        nn.Linear(128, 10)
    )

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    loss_fn = nn.CrossEntropyLoss()

    # Train loop
    for epoch in range(3):
        for x, y in train_loader:
            pred = model(x)
            loss = loss_fn(pred, y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}") # type: ignore


    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for x, y in test_loader:
            pred = model(x)
            pred_labels = pred.argmax(dim=1)
            correct += (pred_labels == y).sum().item()
            total += y.size(0)
    print(f"Test Accuracy: {100 * correct / total:.2f}%")
    
test()

Epoch 0, Loss: 0.1725
Epoch 1, Loss: 0.1720
Epoch 2, Loss: 0.0417
Test Accuracy: 96.73%
